# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-14 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='lists',
            field=models.TextField(default=''),
        ),
    ]
