# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-14 18:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_item_lists'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='lists',
            new_name='list',
        ),
    ]
